// 5. App consists of two parts: form and table. Table should present candidates and their data as it is presented in the picture. The order of the candidates should be based on the votes (highest to lowest). Form input should be required.With form users should be able to add a new candidate. When a new candidate is added, it automatically gets one vote (age and country should be autogenerated).
//If a user enters a name which is already in the list, the app should increment the votes of the current candidate.
//* Every time when candidates votes are changed, the app should arrange their position in the table based on the votes quantity.

// Կիսատ է ցավոք, բայց խոստանում եմ մոտ ապագայում ավարտել


const input = document.querySelector('input')
const button = document.querySelector('input[type=button]')
const name = document.querySelector('.name')
const age = document.querySelector('.age')
const country = document.querySelector('.country')
const voted = document.querySelector('.voted')


function addRow(tableID) {
    let tableRef = document.getElementById(tableID);
  
    let newRow = tableRef.insertRow(-1);
  
    let cell1 = newRow.insertCell(0);
    let cell2 = newRow.insertCell(1);
    let cell3 = newRow.insertCell(2);
    let cell4 = newRow.insertCell(3);
    
    
    cell1.innerText = input.value
    cell2.innerText = Math.floor(Math.random(1) * 91);
    cell3.innerText = 'USA'
}


button.addEventListener('click', ()=> {

    if (input.value !== "") {
        addRow('myTable');
    }
   

    else alert('vote for someone please')
})